# 应用服务 WEB 访问端口
server:
  port: 9091
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/container_number?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 416519
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: true
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2.yml

